### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by taneljuu** [jensjvh/keskustelusovellus#1]
Moi! Tässä olisi muutamia kommentteja sovellukseesi liittyen.

**1. Sovelluksen käyttö**

Sovelluksen käyttö on helppoa ja toimivaa. Navigointi sovelluksessa ja kaikkien toimintojen käyttö onnistuu intuitiivisesti. Ulkoasu on yksinkertaisuudessaan miellyttävä ja tämänkaltaiseen sovellukseen toimiva. 

Sovellus ei säilytä viesteihin lisättyjä rivinvaihtoja. Jos tällaisen ominaisuuden haluaisi lisätä, yksi helppo tapa on tietokantahaun jälkeen pilkkoa viesti esim listaksi rivinvaihtomerkkien kohdalta, ja välittää html-sivulle tämä lista, jolloin rivinvaihdot voi lisätä listan alkioiden väliin. 

En saanut initialize_db.py-tiedoston dataa ajettua, koska sovellus ei jostain syystä löytänyt tietokantayhteyttä .env-tiedostosta. Sain ongelman korjattua lisäämällä db.py-tiedostoon rivit:

from dotenv import load_dotenv
load_dotenv()

Ongelma johtunee koneeni asetuksista, mutta voit halutessasi lisätä readmeen ohjeet tämän ongelman varalle.

**2. Koodi ja rakenne**

Koodi on siistiä, tiivistä ja pythonin käytäntöjen mukaista. Rakenne on myös jaettu järkevästi moduuleihin. Moduulien ja funktioiden toiminnallisuudet on kommentoitu selkeästi ja tiiviisti. Myös html-sivut ovat hyvin toteutettuja.

Istunnon tietojen tarkistus ei kaikissa reiteissä vielä toimi täysin oikein. Esimerkiksi uloskirjautumisen jälkeen pääsee kirjoittamaan viestin edellisen käyttäjän nimissä kirjoittamalla urlin /topics/general_discussion/new_thread. 

Tietokannan rakenne on hyvä ja selkeä, ja tietokannan käsittely eri moduuleissa on hoidettu hyvin ja tehokkaasti.

**Comment by jensjvh** [comment]
Hei, kiitos näistä havainnoista. Korjasin nämä ongelmat!
